name = "ccrouter"
main = "index.ts"
compatibility_date = "2025-05-30"
# routes = [
#   { pattern = "ccrouter.yiguanyaoyaofen.workers.dev", custom_domain = true }
# ]

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1
